version: '3.9'
services:
  php-env:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - 9080:80
    depends_on:
      - db_mysql
  
  db_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linkwit
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db_mysql

# volumes:
#   db_mysql:
  
